apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiserver-servicemonitor.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - prometheus.yaml
  - prometheus-service.yaml
  - prometheus-rules.yaml
  - service-account.yaml